= Personal main takeaways on http://www.metalearn.net/podcasts/ml97-how-to-choose-what-to-learn[Metalearning Podcast #97 - How to Choose What to Learn]

== Passion projects and professional projects

Passion projects are projects that usually requires you to have an
amount of investment (like motivation) but has little to no tangible
return and obvious practical applications. Usually, these passion
projects are often initiated from our hobbies or from our motivation to
act on something. Obviously, this type of project usually starts out as
enjoyable as it's what you want to do. These often stem from our love
for a form of art whether it is mathematics, programming, language,
history, and beyond.

An example of passion projects would depend on the investment that
you're willing to put and the amount of return that you expect. If
you've a passion for the Japanese culture for example, your mind might
have crossed the thought of learning the language. Learning the language
doesn't net you a lot of return as you are working for a non-Japanese
market. However, it does make you not to rely on English patches and
guides when playing a game that's entirely in Japanese.

Professional projects, on the other hand, is the type of projects that
nets you tangible returns such as money, reputation, and advancement.
Unlike passion projects, these are associated with your career and
they're not always fun to do.

An example of such project is making a digital product. You want to earn
money so you built a game and put a fee for users before being able to
play it. The investment eventually returned to you as you continually
update and polish your game. The next thing you found out is people are
paying to play the game you've created.

Most of us tends to have both types of projects. You might have an item
on our passion list about learning a musical instrument so that you can
jam with your friends. Yet, it doesn't practically help you (except when
you make it into a gig or something). It is just for the enjoyment.

=== Practicality, enjoyment, and professionalism

Now this is a major point when it comes to initiating passion projects
and professional projects.

When we want to learn something, usually we make it into a passion
project. Initiating such project for the sake of curiosity, admiration,
or just loving the art, overall. However, doing such a project has a big
gatekeeping resource which is time.

Just as the saying goes...

____
Time is gold.
____

Remember, passion projects are usually projects that doesn't return much
investment that we put in. That is not generally the case as it is
possible for a passion project to have a tangible return. Jumping on
every single thing that excites us might get us to nowhere. Of course,
there are exceptions to the rule and at the end of the day, you are the
best judge on what does this project leads you to.

Having a passion project is fine but we should also think about the
practicality of learning such things for the sake of learning such
things. Just like the host has pointed out, investing in learning a new
skill is like investing in business stocks. Like a good investor, they
would think of the effects on them, the landscape of the economy in the
big picture, and the limited resources that they have in order to have
the best possible return.

We should strategize in using our limited resources (such as time,
money, and focus) and think about the results that it will give us. Like
I said previously, having one or a couple of passion projects is fine
but how are we going to maintain to complete project while doing
everything else? Eventually, that motivation that we have in the start
of the passion project might fade. Coming from that perspective, we
might think that it is all about doing things for the sake of fun.
Conversely, it is better for us to think that there are boring tasks
that we have to deal with and that's completely normal.

Handling things with those perspectives is good and all but there is a
tradeoff that we have to keep in mind, specifically with fulfilling
enjoyment and maintaining your profession. For some of us, it makes more
sense to keep our boring jobs enabling us to do the things that we want.
For others, it is more sensible to make our enjoyment a part of our
professional aspect. When it comes to these things, you are the best
judge to evaluate this as you know the context and the situation.

== Focusing on your strength

Focusing on what you're good at is quite a very important skill to have.
It opens up opportunities that lead you to explore other things. Now
that being said, usually, there are skills developed as a result of the
interest/love of the art but there is also the counterpart case wherein
those skills are developed only because of demands from the job market.
That is the tradeoff that you have to look out for.

Most people are stressing about getting the job doing what they like,
especially if it is their first job. For some of us, that isn't the
case. Sometimes, it is OK to do the boring job in order to make a
living. Having a way to sustain our financial needs is one of the
biggest ways on how we could explore and allow you to do your passion
projects. Maybe we don't want to make our passion to be associated to a
chore or turn into a negative return, maybe we do want it in order to
make a very good and tolerable living. Like I said, be mindful and
cautious about the tradeoffs between enjoyment and practicality that you
could have when considering such things.

It is however possible to have the situation belonging in that tradeoff
spectrum. You could do a project that focuses on your advancing your
skill for your career and have awesome returns from doing the project.
It depends on a lot of factors on how you can acquire such success but
be wary about the resources you could spent and could have spent on
other opportunities that could net more benefits. Like what the host
said, take those statements as a word of caution.

=== Convergent and divergent thinking framework

Although the host only gave a taste of what does it mean to have
divergent and convergent thinking but he does gave a process that uses
these two types of thinking.

The divergent part is listing all of the skills you want to learn
without considerations and filters. Whether it is a skill that is
related to career, personal development, or relationships, you name it.
Just think of all of the skills that you want to learn.

The convergent part is thinking about the skill that could leave you the
most excited. Start with what skill excites you the most then think
about the "why"s, the "how"s, and the other "what"s. Some of the common
questions that you can ask are:

* Why do you want to do it in the first place?
* How does it make you feel?
* What experience can this lead you to?
* What practical effects does learning this particular skill have?
* What kind of opportunities will I get from learning this skill?

== The 3 skills that everyone should learn

=== Self-awareness

This is the ability to reflect about themselves. They are quite aware
about what they should be doing and what they should don't.

The host does not have the magical answer in order to make someone
self-aware. However, he does suggest doing the following in order to
implant the awareness regarding self-awareness:

* daily journalling
* meditation
* asking loved ones about themselves
* doing personality tests

The host also adds that doing these will not give you the answer
regarding being self-aware. However, it does lead you to introspection
and prompting questions that mostly revolves around yourself: what do
you enjoy and not enjoy, what are your strengths and weaknesses, what
skills that could use some leverage, what skills that are not balanced
with the rest of your skills, etc.

=== Understanding the world around you

This could be described as the skill of filtering noise and seeing the
bigger picture. For example, seeing the daily news is not that entirely
helpful (except in some cases) and mostly consists of just noise. Same
with the social media especially when having those types of content like
politics and marketing.

Overall, you should be able to see the bigger picture and where the
world is heading on a macro level. See things on a global scale
regarding to its trends and what trends does it affect your surroundings
(and you, of course). Just spend a little more time paying attention to
the global trends and changes: what types of jobs that could be changing
in the next decade, what is the bigger needs for people in the next 20
years, what technologies that are going to be trending in the near
future, etc. Just keep an eye out for these things because sooner or
later, they're also going to affect you and surely you don't want to be
left out on such things.

=== Learning how to learn

As Nasos (the host) would say, this is mostly considered as the 21st
century superpower. In a ever-changing world where things are coming by
quickly, having the ability to quickly learn and adapt to the skills
that demands it is a very powerful skill to have.

Being aware of the process alone can leave some difference for a person.
Overall, just be aware of your learning process: how would you learn and
what foundational processes are you using can seriously affect the way
and progress you could gather.

As for me, I think that this is also considered as the superpower of
this century. With this skill, you could effective acquire skills.
However, I do want to add that learning how to unlearn and relearn is
just as important as learning how to learn as the world is quite a very
wide field to play. Technology only helps it to be faster on changing.
With these changes, its people have to adapt and we could only hold a
few skills out of a million skills in the skill list.

Anyways, what's more important here is that as long as you could select
the skills that you want to learn, block out all the noise, and just
focus on the learning process, you're good to go. That's the core of
learning how to learn.

While I'm at the topic, I can refer you to one of the Coursera's famous
course, https://www.coursera.org/learn/learning-how-to-learn[Learning
How to Learn], hosted by Barbara Oakley and Terence Sejnowski. You could
also go with the course that follows in its footsteps,
https://www.coursera.org/learn/mindshift[Mindshift: Break Through
Obstacles to Learning and Discover Your Hidden Potential], hosted by the
same hosts only added with Orlando Trejo.
