= Personal main takeaways on https://youarenotsosmart.com/2017/07/25/yanss-105-optimism-bias/[You Are Not So Smart Podcast EP#139 Optimism Bias]

Overall, the podcast episode composes of an interview with Tali Sharot,
the leading director of http://affectivebrain.com/[Affective Brain Lab],
a lab that specializes on neurological and cognitive research. Sharot
also made a https://www.youtube.com/watch?v=B8rmi95pYL0[TED talk on the
subject of the interview]. And as you can tell, David McRaney (the host)
talked with the Affective Lab director about optimism bias.

== What is optimism bias?

Of course, this is the first thing that they've talked about in order to
make an introduction for the listeners. *Optimism bias is a behavior
that leads of a person to make positive reinforcements on the events
that happens and will happen around them or simply just being hopeful.*

Mainly referring from the TED talk, Sharot said that this is a worldwide
phenomena, basically all cultures have a manifestation of this intrinsic
behavior of some kind. Her research with her team indicates that about
80% of us have this bias.

== How does this affects us?

On the first few minutes on their interview, they've talked about how
optimism bias affects how people view themselves and other people. It is
said that this is how people look for the future to be better than the
past and the present.

Now this is not necessarily bad, it really just depends on the person.
Combining that with the reasons given from the TED talk, it could be
because of the following:

* _anticipation_ - this is how people base their views on their side of
future; this is where people become happy or motivated to do something
* _interpretation_ - the results of something and their interpretation
also affects with our optimism bias
* _information_ - given with an information, depending whether it's
given as a positive or negative reinforcement, people will renew their
thoughts differently

Now, to answer the million-dollar question (that is in the sub-header).
This affects us differently - with positive consequences and negative
consequences.

The positive consequences include being motivated for anything: for the
future, for their career, for their health, for their romance, etc. The
most unique ability of a human, according to Sharot, is the capability
to materialize the things that they want to be fully realized.

The future that they look forward to, that's the thing people with such
optimism work for. The positive status of our health we want to achieve
is being achieved as long as we put effort and being motivated by it. In
short, optimism bias gives us the willbeing to do things.

The negative consequences weighs on the amount of optimism that a person
have. Too low and we most likely have some sort of depression but too
much can cause behavioral problems. This include the overestimation of
positive reinforcements that'll apply to them and the underestimation of
negative reinforcement that'll affect them.

For example, if we saw a warning sign about handling voltages of small
amount included with a scientific explanation as to why it is dangerous
despite of its small amount, most of us would underestimate or worse,
completely ignore it and continue with reckless abandon.

== What are the observation of this bias to most of us?

Sharot told the host about an experiment (that is also talked about in
the TED talk) about how people changes perspective depending on the kind
of information that others have passed onto them.

Referring from the TED talk, people tend to not change their perspective
(if not, at least a little) when given with negative reinforcement: an
information that is given as bad news, very conflicting views or
arguments, etc.

On the other hand, most people tend to encode more information on their
mind when positive reinforcements is passed on.

Having this in mind, once people tend to see the positive aspect of
imagining the future, we could have prospection and see the negative
aspect. This is a given statement of a theory from a professor at
University of San Diego, as told by the director of the Affective Brain
Labs.

McRaney had a provoking thought about how does this optimism bias
affects our way of recalling memories.

They say that the way we remember is based on bits of our past
experiences, biases, and information, recreating and basing on these
experiences leads us to create the thing that we try to remember. This
is why when we try to remember a movie trailer, for example, it is said
to have built from what we find as amazing, hype-inducing,
curiosity-piquing, and the like. This is also the reason people remember
things differently through the same event.

Having this optimism bias are said to define our happiness and
wellbeing. The reason why people are quite excited when they got
anticipation for something. The biggest example of this is when people
are planning for a vacation or an adventure. The act of planning alone
induces excitement and happiness for us.

This optimism bias is also observed on animals, being able to anticipate
for the reward that is being given in later future.

The act of planning for the future and imagining that future are what
makes the human to be rising throughout the world when compared to most
animals in their ecosystem. How do you think civilizations rise when
they don't have something to expect?

The ability to envision the future and making the act to realize their
future is the effect of having this bias implanted through most of us.
Ironically, though, this can also be the cause why most of us have a
bias of remembering the past as one of those peaceful times.

Lastly, the amount of optimism bias has a pattern when we base it from
the average age perspective. It is mostly said that the amount of our
optimism gets smaller as we near in our middle 30s. Makes sense as this
is where the time where responsiblity really gets to stack: rearing
children, professional statuses, and taking care of their parents as
they grow into elderhood. However, the amount of optimism gets back up
as we go into elderhood as they have less things to worry about and this
is where most are into retirement.
