= SuperCollider unit generators
Gabriel Arazas <foo.dogsquared@gmail.com>
:revnumber: 0.1
:revdate: 2020-04-17
:revremark: First draft of {doctitle}
:toc:

:stem: latexmath

:name: SuperCollider
:version: 3.11.0


Unit generators, as it turns out (in my research), is a concept inherited from https://en.wikipedia.org/wiki/MUSIC-N[MUSIC-N]-inspired systems. 
**Unit generators** (or **ugens** in short) are the basic building blocks for {name} in order to do sound synthesis. 
In this note, we will inspect how ugens interact with the system. 

NOTE: For future references, the version this note is referring is at {version}. 
We'll also use the SuperCollider IDE to get us on the same page. 




== What is a unit generator? 

**Unit generators** (also called as ugens) are a way of generating and controlling sounds in {name}. 

If you've seen tutorials (or even in my link:introduction-to-supercollider[introduction note to {name}]), chances are you've already used it. 
The most basic example that is most likely presented is the sine wave ugen which simply generates a sine wave. 

[source, supercollider]
----
{SinOsc.ar(440, mul: 0.6)}.play;
----

We could even combine unit generators to create a more distinct sound. 
The following code will produce similar to old-style telephone rings. 

[source, supercollider]
----
{SinOsc.ar(440, mul: SinOsc.ar(20, mul: 0.8))}.play;
----

We could also create interactive pieces with ugens. 
For example, a theremin (or at least a simulation of it). 

[source, supercollider]
----
{SinOsc.ar(freq: MouseX.kr(minval: 300, maxval: 1000), mul: MouseY.kr(minval: 0, maxval: 1))}.play;
----

We're introduced to two new unit generators: `MouseX` and `MouseY`. 
These are intuitively self-explanatory. 
The given ugens generates signal according to your X (horizontal) and Y (vertical) position of the mouse cursor, respectively. 

To know more unit generators, the {name} community has written https://doc.sccode.org/Guides/Tour_of_UGens.html[a dedicated section listing all (if not most) unit generators] in neat and composed groups. 
(It should be included on the built-in documentations, too.) 

Let's go with one little exercise: change the sine wave from the theremin simulation into a saw wave. 
You could also change the other examples into something else and try to be out of comfort zone into creating more alien and distinct sounds. 




== Audio and control rate 

Spotting a ugen is fortunately easy. 
All of unit generators have the `ar` and `kr` methods which is inherited by a superclass named https://doc.sccode.org/Classes/UGen.html[`UGen`]. 
The methods causes the ugens to be created that runs on the audio (`ar`) or control (`kr`) rate. 

If the computer is configured at 44 KHz (kilohertz) as the audio rate, the ugen created with the `ar` message will produce 44000 samples per second. 

Ugens that runs on control rate on the other hand, generates less samples per second compared to the audio rate. 
Since it generates less, it uses less processing power and does not generate an audible sound. 
Practically, this is often used for applying effects or generating low frequencies. 

[source, supercollider]
----
SinOsc.ar(freq: 500, mul: SinOsc.kr(40));
----

We've already said that a ugen generates samples. 
What are these samples to be exact? 
They are simply numbers ranging from -1 to 1 (or sometimes 0 to 1). 

Let's take a peek for ourselves with the following samples: 

[source, supercollider]
----
// This will log some output of the generated samples. 
{SinOsc.ar(1).poll}.play;
----

Since the ugen generates samples at an audio rate, it should generate 44,000 samples per second but we don't want to see 44,000 lines logged per second. 
For this, we simply request to get some of the samples with `.poll`. 

The sine wave ugen generates from -1 to 1. 
From the example, try to replace the frequency of the ugen with higher numbers and see the difference between each iteration. 
We could also test with other unit generators like http://doc.sccode.org/Classes/LFNoise0.html[`LFNoise0`], http://doc.sccode.org/Classes/Pulse.html[`Pulse`], or http://doc.sccode.org/Classes/Blip.html[`Blip`]. 




== Common arguments of a ugen 

Ugens often have some common arguments. 
For example, the sine wave example from the previous code block uses the `freq` and `mul` arguments (which happens to be two of the most common arguments for creating audio signals). 
The `freq` dictates how many sine waves to generate per second. 
Essentially, this is used for the tone. 
Meanwhile, `mul` is practically the amplitude of the resulting soundwave. 
Having a `mul` of `0.5` means the soundwave is multiplied by half. 

There's also another common argument called `add` which simply adds the specified value to the total output signal. 
Let's modify the telephone example. 

[source, supercollider]
----
{SinOsc.ar(freq: 440, mul: SinOsc.ar(20, mul: 0.8), add: 0.3)}.play
----

If you have the scope on (with `s.scope`), you would see the output is elevated slightly.

It is more preferred of being explicit with the argument names. 
Explicitly naming arguments also lets you skip between parameters. 
If we're to do the example without naming, we would have to do the following: 

[source, supercollider]
----
SinOsc.ar(500, 0, 40);
----

The second parameter (named `phase`) specifies the initial point when playing the sine wave. 
To know the arguments that a ugen accept, just go to the appropriate help section. 
In this example, we can clearly see from the https://doc.sccode.org/Classes/SinOsc.html[`SinOsc`] that it can accept 4 arguments (with default values). 

If you're using the {name} IDE, you can easily get to the documentation of the ugen by pressing `Ctrl + D` (assuming the default settings). 




== Synths 

What does synths have to do with unit generators? 
They are needed to play the ugen. 

But hold on, didn't we already create sounds with ugens? 
Well, yes! 

[source, supercollider]
----
{SinOsc.ar}.play;
----

Take a look at the post window/logged results. 
Very familiar, right? 

[source]
----
Synth('temp__52' : 1032)
----

It turns out `.play` message does something more than simply passing the result to the server but let's take a gander what synths are. 

A **synth**, as taken from the http://doc.sccode.org/Guides/UGens-and-Synths.html[official documentation], is a container for one or more ugens. 
Before we make use of synths, it should be defined first through http://doc.sccode.org/Classes/SynthDef.html[`SynthDef`]. 

[source, supercollider]
----
SynthDef.new(\telephone, { Out.ar(0, SinOsc.ar(freq: 440, mul: SinOsc.kr(20))) });

// Create a synth node on the server.
x = Synth.new(\telephone);

// Stopping the synth node output.
x.run(false);

// Deleting the synth node on the server.
x.free;
----

We could make the synth more dynamic and complex by defining arguments and combining ugens. 

[source, supercollider]
----
// A more dynamic telephone synth. 
(
SynthDef.new(\telephone, { 
    |out = 0, freq = 440, control_rate = 20|

    Out.ar(out, SinOsc.ar(freq, mul: SinOsc.kr(control_rate)));
}).add;
)

// Creating a telephone synth with different parameters. 
(
x = Synth.new(\telephone, [
    \freq, 220,
    \control_rate, 15
]);
)
----




[appendix]
== Additional readings

https://ccrma.stanford.edu/~ruviaro/texts/A_Gentle_Introduction_To_SuperCollider.pdf[__A gentle introduction to {name}__ by "Bruno Ruviaro"] (retrieved 2020-04-18):: 
My go-to introductory reference for {name}. 
I find it more intuitive than the official tutorial having absolute zero experience with audio systems (aside from using https://lmms.io/[LMMS] on and off) especially with the introduction to unit generators and other major components. 

https://doc.sccode.org/Guides/Tour_of_UGens.html[__Tour of ugens__ from the official documentation] (retrieved 2020-04-18):: 
A quick tour of the unit generators {name} provides out of its 250 ugens. 
It gives a good starting point for your go-to ugens. 

